// Generated by tools/generate_accumulating.py; do not edit by hand.

package com.flechazo.hkt.business.control;

import com.flechazo.hkt.Validated;
import com.flechazo.hkt.business.capability.Accumulating;
import com.flechazo.hkt.function.*;
import com.flechazo.hkt.tuple.Tuple2;

import java.util.function.BiFunction;

interface ValidationAccumulating<E, A> extends Accumulating<E, A> {
    @Override
    default <B, R> ValidationPath<E, R> zipWithAccum(
            Accumulating<E, B> other,
            BiFunction<? super A, ? super B, ? extends R> combiner) {
        if (!(other instanceof ValidationPath<?, ?>)) {
            throw new IllegalArgumentException("zipWithAccum requires ValidationPath, got: " + other.getClass());
        }
        ValidationPath<E, A> left = self();
        ValidationPath<E, B> right = narrow(other);
        Validated<E, A> leftValue = left.run();
        Validated<E, B> rightValue = right.run();
        if (leftValue.isValid() && rightValue.isValid()) {
            return new ValidationPath<>(
                    Validated.valid(combiner.apply(leftValue.value(), rightValue.value())),
                    left.semigroup());
        }
        if (leftValue.isInvalid() && rightValue.isInvalid()) {
            return new ValidationPath<>(
                    Validated.invalid(left.semigroup().combine(leftValue.error(), rightValue.error())),
                    left.semigroup());
        }
        return leftValue.isInvalid()
                ? new ValidationPath<>(Validated.invalid(leftValue.error()), left.semigroup())
                : new ValidationPath<>(Validated.invalid(rightValue.error()), left.semigroup());
    }

    @Override
    default <B, C, R> ValidationPath<E, R> zipWith3Accum(
            Accumulating<E, B> second,
            Accumulating<E, C> third,
            Function3<? super A, ? super B, ? super C, ? extends R> combiner) {
        return zipWithAccum(second, Tuple2::new)
                .zipWithAccum(third,
                        (values, value) -> combiner.apply(values.first(), values.second(), value));
    }

    @Override
    default <T2, T3, T4, R> ValidationPath<E, R> zipWith4Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Function4<? super A, ? super T2, ? super T3, ? super T4, ? extends R> combiner) {
        return narrow(Accumulating.super.zipWith4Accum(second, third, fourth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, R> ValidationPath<E, R> zipWith5Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Function5<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? extends R> combiner) {
        return narrow(Accumulating.super.zipWith5Accum(second, third, fourth, fifth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, R> ValidationPath<E, R> zipWith6Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Function6<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? extends R> combiner) {
        return narrow(Accumulating.super.zipWith6Accum(second, third, fourth, fifth, sixth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, R> ValidationPath<E, R> zipWith7Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Function7<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? extends R> combiner) {
        return narrow(Accumulating.super.zipWith7Accum(second, third, fourth, fifth, sixth, seventh, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, T8, R> ValidationPath<E, R> zipWith8Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Accumulating<E, T8> eighth,
            Function8<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? extends R> combiner) {
        return narrow(Accumulating.super.zipWith8Accum(second, third, fourth, fifth, sixth, seventh, eighth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, T8, T9, R> ValidationPath<E, R> zipWith9Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Accumulating<E, T8> eighth,
            Accumulating<E, T9> ninth,
            Function9<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? extends R> combiner) {
        return narrow(Accumulating.super.zipWith9Accum(second, third, fourth, fifth, sixth, seventh, eighth, ninth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, R> ValidationPath<E, R> zipWith10Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Accumulating<E, T8> eighth,
            Accumulating<E, T9> ninth,
            Accumulating<E, T10> tenth,
            Function10<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? extends R> combiner) {
        return narrow(Accumulating.super.zipWith10Accum(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, R> ValidationPath<E, R> zipWith11Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Accumulating<E, T8> eighth,
            Accumulating<E, T9> ninth,
            Accumulating<E, T10> tenth,
            Accumulating<E, T11> eleventh,
            Function11<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? extends R> combiner) {
        return narrow(Accumulating.super.zipWith11Accum(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, R> ValidationPath<E, R> zipWith12Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Accumulating<E, T8> eighth,
            Accumulating<E, T9> ninth,
            Accumulating<E, T10> tenth,
            Accumulating<E, T11> eleventh,
            Accumulating<E, T12> twelfth,
            Function12<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? extends R> combiner) {
        return narrow(Accumulating.super.zipWith12Accum(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, R> ValidationPath<E, R> zipWith13Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Accumulating<E, T8> eighth,
            Accumulating<E, T9> ninth,
            Accumulating<E, T10> tenth,
            Accumulating<E, T11> eleventh,
            Accumulating<E, T12> twelfth,
            Accumulating<E, T13> thirteenth,
            Function13<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? extends R> combiner) {
        return narrow(Accumulating.super.zipWith13Accum(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, R> ValidationPath<E, R> zipWith14Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Accumulating<E, T8> eighth,
            Accumulating<E, T9> ninth,
            Accumulating<E, T10> tenth,
            Accumulating<E, T11> eleventh,
            Accumulating<E, T12> twelfth,
            Accumulating<E, T13> thirteenth,
            Accumulating<E, T14> fourteenth,
            Function14<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? super T14, ? extends R> combiner) {
        return narrow(Accumulating.super.zipWith14Accum(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth, fourteenth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, R> ValidationPath<E, R> zipWith15Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Accumulating<E, T8> eighth,
            Accumulating<E, T9> ninth,
            Accumulating<E, T10> tenth,
            Accumulating<E, T11> eleventh,
            Accumulating<E, T12> twelfth,
            Accumulating<E, T13> thirteenth,
            Accumulating<E, T14> fourteenth,
            Accumulating<E, T15> fifteenth,
            Function15<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? super T14, ? super T15, ? extends R> combiner) {
        return narrow(Accumulating.super.zipWith15Accum(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth, fourteenth, fifteenth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, R> ValidationPath<E, R> zipWith16Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Accumulating<E, T8> eighth,
            Accumulating<E, T9> ninth,
            Accumulating<E, T10> tenth,
            Accumulating<E, T11> eleventh,
            Accumulating<E, T12> twelfth,
            Accumulating<E, T13> thirteenth,
            Accumulating<E, T14> fourteenth,
            Accumulating<E, T15> fifteenth,
            Accumulating<E, T16> sixteenth,
            Function16<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? super T14, ? super T15, ? super T16, ? extends R> combiner) {
        return narrow(Accumulating.super.zipWith16Accum(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth, fourteenth, fifteenth, sixteenth, combiner));
    }

    private ValidationPath<E, A> self() {
        return (ValidationPath<E, A>) this;
    }

    private static <E, A> ValidationPath<E, A> narrow(Accumulating<E, A> value) {
        return (ValidationPath<E, A>) value;
    }
}
