// Generated by tools/generate_combinable.py; do not edit by hand.

package com.flechazo.hkt.business.capability.combinable;

import com.flechazo.hkt.business.capability.Composable;
import com.flechazo.hkt.function.*;
import com.flechazo.hkt.tuple.*;

import java.util.function.BiFunction;

public interface Combinable<A> extends Composable<A> {
    <B, R> Combinable<R> zipWith(
            Combinable<B> other,
            BiFunction<? super A, ? super B, ? extends R> combiner);

    default <T2, T3, OUT> Combinable<OUT> zipWith3(
            Combinable<T2> second,
            Combinable<T3> third,
            Function3<? super A, ? super T2, ? super T3, ? extends OUT> combiner) {
        Combinable<Tuple2<A, T2>> partial =
                zipWith(second, Tuple2::new);
        return partial.zipWith(third,
                (values, value) -> combiner.apply(values.first(), values.second(), value));
    }

    default <T2, T3, T4, OUT> Combinable<OUT> zipWith4(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Function4<? super A, ? super T2, ? super T3, ? super T4, ? extends OUT> combiner) {
        Combinable<Tuple3<A, T2, T3>> partial =
                zipWith3(second, third, Tuple3::of);
        return partial.zipWith(fourth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), value));
    }

    default <T2, T3, T4, T5, OUT> Combinable<OUT> zipWith5(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Function5<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? extends OUT> combiner) {
        Combinable<Tuple4<A, T2, T3, T4>> partial =
                zipWith4(second, third, fourth, Tuple4::of);
        return partial.zipWith(fifth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), value));
    }

    default <T2, T3, T4, T5, T6, OUT> Combinable<OUT> zipWith6(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Function6<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? extends OUT> combiner) {
        Combinable<Tuple5<A, T2, T3, T4, T5>> partial =
                zipWith5(second, third, fourth, fifth, Tuple5::of);
        return partial.zipWith(sixth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), value));
    }

    default <T2, T3, T4, T5, T6, T7, OUT> Combinable<OUT> zipWith7(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Function7<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? extends OUT> combiner) {
        Combinable<Tuple6<A, T2, T3, T4, T5, T6>> partial =
                zipWith6(second, third, fourth, fifth, sixth, Tuple6::of);
        return partial.zipWith(seventh,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), value));
    }

    default <T2, T3, T4, T5, T6, T7, T8, OUT> Combinable<OUT> zipWith8(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Combinable<T8> eighth,
            Function8<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? extends OUT> combiner) {
        Combinable<Tuple7<A, T2, T3, T4, T5, T6, T7>> partial =
                zipWith7(second, third, fourth, fifth, sixth, seventh, Tuple7::of);
        return partial.zipWith(eighth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), values.seventh(), value));
    }

    default <T2, T3, T4, T5, T6, T7, T8, T9, OUT> Combinable<OUT> zipWith9(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Combinable<T8> eighth,
            Combinable<T9> ninth,
            Function9<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? extends OUT> combiner) {
        Combinable<Tuple8<A, T2, T3, T4, T5, T6, T7, T8>> partial =
                zipWith8(second, third, fourth, fifth, sixth, seventh, eighth, Tuple8::of);
        return partial.zipWith(ninth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), values.seventh(), values.eighth(), value));
    }

    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, OUT> Combinable<OUT> zipWith10(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Combinable<T8> eighth,
            Combinable<T9> ninth,
            Combinable<T10> tenth,
            Function10<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? extends OUT> combiner) {
        Combinable<Tuple9<A, T2, T3, T4, T5, T6, T7, T8, T9>> partial =
                zipWith9(second, third, fourth, fifth, sixth, seventh, eighth, ninth, Tuple9::of);
        return partial.zipWith(tenth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), values.seventh(), values.eighth(), values.ninth(), value));
    }

    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, OUT> Combinable<OUT> zipWith11(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Combinable<T8> eighth,
            Combinable<T9> ninth,
            Combinable<T10> tenth,
            Combinable<T11> eleventh,
            Function11<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? extends OUT> combiner) {
        Combinable<Tuple10<A, T2, T3, T4, T5, T6, T7, T8, T9, T10>> partial =
                zipWith10(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, Tuple10::of);
        return partial.zipWith(eleventh,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), values.seventh(), values.eighth(), values.ninth(), values.tenth(), value));
    }

    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, OUT> Combinable<OUT> zipWith12(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Combinable<T8> eighth,
            Combinable<T9> ninth,
            Combinable<T10> tenth,
            Combinable<T11> eleventh,
            Combinable<T12> twelfth,
            Function12<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? extends OUT> combiner) {
        Combinable<Tuple11<A, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>> partial =
                zipWith11(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, Tuple11::of);
        return partial.zipWith(twelfth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), values.seventh(), values.eighth(), values.ninth(), values.tenth(), values.eleventh(), value));
    }

    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, OUT> Combinable<OUT> zipWith13(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Combinable<T8> eighth,
            Combinable<T9> ninth,
            Combinable<T10> tenth,
            Combinable<T11> eleventh,
            Combinable<T12> twelfth,
            Combinable<T13> thirteenth,
            Function13<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? extends OUT> combiner) {
        Combinable<Tuple12<A, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>> partial =
                zipWith12(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, Tuple12::of);
        return partial.zipWith(thirteenth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), values.seventh(), values.eighth(), values.ninth(), values.tenth(), values.eleventh(), values.twelfth(), value));
    }

    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, OUT> Combinable<OUT> zipWith14(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Combinable<T8> eighth,
            Combinable<T9> ninth,
            Combinable<T10> tenth,
            Combinable<T11> eleventh,
            Combinable<T12> twelfth,
            Combinable<T13> thirteenth,
            Combinable<T14> fourteenth,
            Function14<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? super T14, ? extends OUT> combiner) {
        Combinable<Tuple13<A, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>> partial =
                zipWith13(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth, Tuple13::of);
        return partial.zipWith(fourteenth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), values.seventh(), values.eighth(), values.ninth(), values.tenth(), values.eleventh(), values.twelfth(), values.thirteenth(), value));
    }

    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, OUT> Combinable<OUT> zipWith15(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Combinable<T8> eighth,
            Combinable<T9> ninth,
            Combinable<T10> tenth,
            Combinable<T11> eleventh,
            Combinable<T12> twelfth,
            Combinable<T13> thirteenth,
            Combinable<T14> fourteenth,
            Combinable<T15> fifteenth,
            Function15<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? super T14, ? super T15, ? extends OUT> combiner) {
        Combinable<Tuple14<A, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>> partial =
                zipWith14(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth, fourteenth, Tuple14::of);
        return partial.zipWith(fifteenth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), values.seventh(), values.eighth(), values.ninth(), values.tenth(), values.eleventh(), values.twelfth(), values.thirteenth(), values.fourteenth(), value));
    }

    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, OUT> Combinable<OUT> zipWith16(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Combinable<T8> eighth,
            Combinable<T9> ninth,
            Combinable<T10> tenth,
            Combinable<T11> eleventh,
            Combinable<T12> twelfth,
            Combinable<T13> thirteenth,
            Combinable<T14> fourteenth,
            Combinable<T15> fifteenth,
            Combinable<T16> sixteenth,
            Function16<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? super T14, ? super T15, ? super T16, ? extends OUT> combiner) {
        Combinable<Tuple15<A, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>> partial =
                zipWith15(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth, fourteenth, fifteenth, Tuple15::of);
        return partial.zipWith(sixteenth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), values.seventh(), values.eighth(), values.ninth(), values.tenth(), values.eleventh(), values.twelfth(), values.thirteenth(), values.fourteenth(), values.fifteenth(), value));
    }

}
