// Generated by tools/generate_combinable.py; do not edit by hand.

package com.flechazo.hkt.business.capability.combinable;

import com.flechazo.hkt.business.capability.combinable.Combinable;
import com.flechazo.hkt.business.context.WriterPath;
import com.flechazo.hkt.function.*;

public interface WriterCombinable<W, A> extends Combinable<A> {
    @Override
    default <T2, T3, OUT> WriterPath<W, OUT> zipWith3(
            Combinable<T2> second,
            Combinable<T3> third,
            Function3<? super A, ? super T2, ? super T3, ? extends OUT> combiner) {
        return narrow(Combinable.super.zipWith3(second, third, combiner));
    }

    @Override
    default <T2, T3, T4, OUT> WriterPath<W, OUT> zipWith4(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Function4<? super A, ? super T2, ? super T3, ? super T4, ? extends OUT> combiner) {
        return narrow(Combinable.super.zipWith4(second, third, fourth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, OUT> WriterPath<W, OUT> zipWith5(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Function5<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? extends OUT> combiner) {
        return narrow(Combinable.super.zipWith5(second, third, fourth, fifth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, OUT> WriterPath<W, OUT> zipWith6(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Function6<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? extends OUT> combiner) {
        return narrow(Combinable.super.zipWith6(second, third, fourth, fifth, sixth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, OUT> WriterPath<W, OUT> zipWith7(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Function7<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? extends OUT> combiner) {
        return narrow(Combinable.super.zipWith7(second, third, fourth, fifth, sixth, seventh, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, T8, OUT> WriterPath<W, OUT> zipWith8(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Combinable<T8> eighth,
            Function8<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? extends OUT> combiner) {
        return narrow(Combinable.super.zipWith8(second, third, fourth, fifth, sixth, seventh, eighth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, T8, T9, OUT> WriterPath<W, OUT> zipWith9(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Combinable<T8> eighth,
            Combinable<T9> ninth,
            Function9<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? extends OUT> combiner) {
        return narrow(Combinable.super.zipWith9(second, third, fourth, fifth, sixth, seventh, eighth, ninth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, OUT> WriterPath<W, OUT> zipWith10(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Combinable<T8> eighth,
            Combinable<T9> ninth,
            Combinable<T10> tenth,
            Function10<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? extends OUT> combiner) {
        return narrow(Combinable.super.zipWith10(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, OUT> WriterPath<W, OUT> zipWith11(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Combinable<T8> eighth,
            Combinable<T9> ninth,
            Combinable<T10> tenth,
            Combinable<T11> eleventh,
            Function11<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? extends OUT> combiner) {
        return narrow(Combinable.super.zipWith11(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, OUT> WriterPath<W, OUT> zipWith12(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Combinable<T8> eighth,
            Combinable<T9> ninth,
            Combinable<T10> tenth,
            Combinable<T11> eleventh,
            Combinable<T12> twelfth,
            Function12<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? extends OUT> combiner) {
        return narrow(Combinable.super.zipWith12(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, OUT> WriterPath<W, OUT> zipWith13(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Combinable<T8> eighth,
            Combinable<T9> ninth,
            Combinable<T10> tenth,
            Combinable<T11> eleventh,
            Combinable<T12> twelfth,
            Combinable<T13> thirteenth,
            Function13<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? extends OUT> combiner) {
        return narrow(Combinable.super.zipWith13(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, OUT> WriterPath<W, OUT> zipWith14(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Combinable<T8> eighth,
            Combinable<T9> ninth,
            Combinable<T10> tenth,
            Combinable<T11> eleventh,
            Combinable<T12> twelfth,
            Combinable<T13> thirteenth,
            Combinable<T14> fourteenth,
            Function14<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? super T14, ? extends OUT> combiner) {
        return narrow(Combinable.super.zipWith14(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth, fourteenth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, OUT> WriterPath<W, OUT> zipWith15(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Combinable<T8> eighth,
            Combinable<T9> ninth,
            Combinable<T10> tenth,
            Combinable<T11> eleventh,
            Combinable<T12> twelfth,
            Combinable<T13> thirteenth,
            Combinable<T14> fourteenth,
            Combinable<T15> fifteenth,
            Function15<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? super T14, ? super T15, ? extends OUT> combiner) {
        return narrow(Combinable.super.zipWith15(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth, fourteenth, fifteenth, combiner));
    }

    @Override
    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, OUT> WriterPath<W, OUT> zipWith16(
            Combinable<T2> second,
            Combinable<T3> third,
            Combinable<T4> fourth,
            Combinable<T5> fifth,
            Combinable<T6> sixth,
            Combinable<T7> seventh,
            Combinable<T8> eighth,
            Combinable<T9> ninth,
            Combinable<T10> tenth,
            Combinable<T11> eleventh,
            Combinable<T12> twelfth,
            Combinable<T13> thirteenth,
            Combinable<T14> fourteenth,
            Combinable<T15> fifteenth,
            Combinable<T16> sixteenth,
            Function16<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? super T14, ? super T15, ? super T16, ? extends OUT> combiner) {
        return narrow(Combinable.super.zipWith16(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth, fourteenth, fifteenth, sixteenth, combiner));
    }

    private static <W, A> WriterPath<W, A> narrow(
            Combinable<A> value) {
        return (WriterPath<W, A>) value;
    }
}
