// Generated by tools/generate_tuples.py; do not edit by hand.

package com.flechazo.hkt.tuple;

import com.flechazo.hkt.function.Function12;

import java.util.Objects;
import java.util.function.Function;

public record Tuple12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(
        T1 first,
        T2 second,
        T3 third,
        T4 fourth,
        T5 fifth,
        T6 sixth,
        T7 seventh,
        T8 eighth,
        T9 ninth,
        T10 tenth,
        T11 eleventh,
        T12 twelfth) {
    public Tuple12 {
        Objects.requireNonNull(first, "first");
        Objects.requireNonNull(second, "second");
        Objects.requireNonNull(third, "third");
        Objects.requireNonNull(fourth, "fourth");
        Objects.requireNonNull(fifth, "fifth");
        Objects.requireNonNull(sixth, "sixth");
        Objects.requireNonNull(seventh, "seventh");
        Objects.requireNonNull(eighth, "eighth");
        Objects.requireNonNull(ninth, "ninth");
        Objects.requireNonNull(tenth, "tenth");
        Objects.requireNonNull(eleventh, "eleventh");
        Objects.requireNonNull(twelfth, "twelfth");
    }

    public static <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> Tuple12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> of(
            T1 first,
            T2 second,
            T3 third,
            T4 fourth,
            T5 fifth,
            T6 sixth,
            T7 seventh,
            T8 eighth,
            T9 ninth,
            T10 tenth,
            T11 eleventh,
            T12 twelfth) {
        return new Tuple12<>(first, second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth);
    }

    public <R1> Tuple12<R1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> mapFirst(
            Function<? super T1, ? extends R1> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple12<>(mapper.apply(first), second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth);
    }

    public <R2> Tuple12<T1, R2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> mapSecond(
            Function<? super T2, ? extends R2> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple12<>(first, mapper.apply(second), third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth);
    }

    public <R3> Tuple12<T1, T2, R3, T4, T5, T6, T7, T8, T9, T10, T11, T12> mapThird(
            Function<? super T3, ? extends R3> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple12<>(first, second, mapper.apply(third), fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth);
    }

    public <R4> Tuple12<T1, T2, T3, R4, T5, T6, T7, T8, T9, T10, T11, T12> mapFourth(
            Function<? super T4, ? extends R4> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple12<>(first, second, third, mapper.apply(fourth), fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth);
    }

    public <R5> Tuple12<T1, T2, T3, T4, R5, T6, T7, T8, T9, T10, T11, T12> mapFifth(
            Function<? super T5, ? extends R5> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple12<>(first, second, third, fourth, mapper.apply(fifth), sixth, seventh, eighth, ninth, tenth, eleventh, twelfth);
    }

    public <R6> Tuple12<T1, T2, T3, T4, T5, R6, T7, T8, T9, T10, T11, T12> mapSixth(
            Function<? super T6, ? extends R6> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple12<>(first, second, third, fourth, fifth, mapper.apply(sixth), seventh, eighth, ninth, tenth, eleventh, twelfth);
    }

    public <R7> Tuple12<T1, T2, T3, T4, T5, T6, R7, T8, T9, T10, T11, T12> mapSeventh(
            Function<? super T7, ? extends R7> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple12<>(first, second, third, fourth, fifth, sixth, mapper.apply(seventh), eighth, ninth, tenth, eleventh, twelfth);
    }

    public <R8> Tuple12<T1, T2, T3, T4, T5, T6, T7, R8, T9, T10, T11, T12> mapEighth(
            Function<? super T8, ? extends R8> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple12<>(first, second, third, fourth, fifth, sixth, seventh, mapper.apply(eighth), ninth, tenth, eleventh, twelfth);
    }

    public <R9> Tuple12<T1, T2, T3, T4, T5, T6, T7, T8, R9, T10, T11, T12> mapNinth(
            Function<? super T9, ? extends R9> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple12<>(first, second, third, fourth, fifth, sixth, seventh, eighth, mapper.apply(ninth), tenth, eleventh, twelfth);
    }

    public <R10> Tuple12<T1, T2, T3, T4, T5, T6, T7, T8, T9, R10, T11, T12> mapTenth(
            Function<? super T10, ? extends R10> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple12<>(first, second, third, fourth, fifth, sixth, seventh, eighth, ninth, mapper.apply(tenth), eleventh, twelfth);
    }

    public <R11> Tuple12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R11, T12> mapEleventh(
            Function<? super T11, ? extends R11> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple12<>(first, second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, mapper.apply(eleventh), twelfth);
    }

    public <R12> Tuple12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, R12> mapTwelfth(
            Function<? super T12, ? extends R12> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple12<>(first, second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, mapper.apply(twelfth));
    }

    public <R> R fold(Function12<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? extends R> function) {
        Objects.requireNonNull(function, "function");
        return function.apply(first, second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth);
    }
}
