// Generated by tools/generate_tuples.py; do not edit by hand.

package com.flechazo.hkt.tuple;

import com.flechazo.hkt.function.Function10;

import java.util.Objects;
import java.util.function.Function;

public record Tuple10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(
        T1 first,
        T2 second,
        T3 third,
        T4 fourth,
        T5 fifth,
        T6 sixth,
        T7 seventh,
        T8 eighth,
        T9 ninth,
        T10 tenth) {
    public Tuple10 {
        Objects.requireNonNull(first, "first");
        Objects.requireNonNull(second, "second");
        Objects.requireNonNull(third, "third");
        Objects.requireNonNull(fourth, "fourth");
        Objects.requireNonNull(fifth, "fifth");
        Objects.requireNonNull(sixth, "sixth");
        Objects.requireNonNull(seventh, "seventh");
        Objects.requireNonNull(eighth, "eighth");
        Objects.requireNonNull(ninth, "ninth");
        Objects.requireNonNull(tenth, "tenth");
    }

    public static <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> Tuple10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> of(
            T1 first,
            T2 second,
            T3 third,
            T4 fourth,
            T5 fifth,
            T6 sixth,
            T7 seventh,
            T8 eighth,
            T9 ninth,
            T10 tenth) {
        return new Tuple10<>(first, second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth);
    }

    public <R1> Tuple10<R1, T2, T3, T4, T5, T6, T7, T8, T9, T10> mapFirst(
            Function<? super T1, ? extends R1> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple10<>(mapper.apply(first), second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth);
    }

    public <R2> Tuple10<T1, R2, T3, T4, T5, T6, T7, T8, T9, T10> mapSecond(
            Function<? super T2, ? extends R2> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple10<>(first, mapper.apply(second), third, fourth, fifth, sixth, seventh, eighth, ninth, tenth);
    }

    public <R3> Tuple10<T1, T2, R3, T4, T5, T6, T7, T8, T9, T10> mapThird(
            Function<? super T3, ? extends R3> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple10<>(first, second, mapper.apply(third), fourth, fifth, sixth, seventh, eighth, ninth, tenth);
    }

    public <R4> Tuple10<T1, T2, T3, R4, T5, T6, T7, T8, T9, T10> mapFourth(
            Function<? super T4, ? extends R4> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple10<>(first, second, third, mapper.apply(fourth), fifth, sixth, seventh, eighth, ninth, tenth);
    }

    public <R5> Tuple10<T1, T2, T3, T4, R5, T6, T7, T8, T9, T10> mapFifth(
            Function<? super T5, ? extends R5> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple10<>(first, second, third, fourth, mapper.apply(fifth), sixth, seventh, eighth, ninth, tenth);
    }

    public <R6> Tuple10<T1, T2, T3, T4, T5, R6, T7, T8, T9, T10> mapSixth(
            Function<? super T6, ? extends R6> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple10<>(first, second, third, fourth, fifth, mapper.apply(sixth), seventh, eighth, ninth, tenth);
    }

    public <R7> Tuple10<T1, T2, T3, T4, T5, T6, R7, T8, T9, T10> mapSeventh(
            Function<? super T7, ? extends R7> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple10<>(first, second, third, fourth, fifth, sixth, mapper.apply(seventh), eighth, ninth, tenth);
    }

    public <R8> Tuple10<T1, T2, T3, T4, T5, T6, T7, R8, T9, T10> mapEighth(
            Function<? super T8, ? extends R8> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple10<>(first, second, third, fourth, fifth, sixth, seventh, mapper.apply(eighth), ninth, tenth);
    }

    public <R9> Tuple10<T1, T2, T3, T4, T5, T6, T7, T8, R9, T10> mapNinth(
            Function<? super T9, ? extends R9> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple10<>(first, second, third, fourth, fifth, sixth, seventh, eighth, mapper.apply(ninth), tenth);
    }

    public <R10> Tuple10<T1, T2, T3, T4, T5, T6, T7, T8, T9, R10> mapTenth(
            Function<? super T10, ? extends R10> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple10<>(first, second, third, fourth, fifth, sixth, seventh, eighth, ninth, mapper.apply(tenth));
    }

    public <R> R fold(Function10<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? extends R> function) {
        Objects.requireNonNull(function, "function");
        return function.apply(first, second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth);
    }
}
