// Generated by tools/generate_tuples.py; do not edit by hand.

package com.flechazo.hkt.tuple;

import com.flechazo.hkt.function.Function5;

import java.util.Objects;
import java.util.function.Function;

public record Tuple5<T1, T2, T3, T4, T5>(
        T1 first,
        T2 second,
        T3 third,
        T4 fourth,
        T5 fifth) {
    public Tuple5 {
        Objects.requireNonNull(first, "first");
        Objects.requireNonNull(second, "second");
        Objects.requireNonNull(third, "third");
        Objects.requireNonNull(fourth, "fourth");
        Objects.requireNonNull(fifth, "fifth");
    }

    public static <T1, T2, T3, T4, T5> Tuple5<T1, T2, T3, T4, T5> of(
            T1 first,
            T2 second,
            T3 third,
            T4 fourth,
            T5 fifth) {
        return new Tuple5<>(first, second, third, fourth, fifth);
    }

    public <R1> Tuple5<R1, T2, T3, T4, T5> mapFirst(
            Function<? super T1, ? extends R1> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple5<>(mapper.apply(first), second, third, fourth, fifth);
    }

    public <R2> Tuple5<T1, R2, T3, T4, T5> mapSecond(
            Function<? super T2, ? extends R2> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple5<>(first, mapper.apply(second), third, fourth, fifth);
    }

    public <R3> Tuple5<T1, T2, R3, T4, T5> mapThird(
            Function<? super T3, ? extends R3> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple5<>(first, second, mapper.apply(third), fourth, fifth);
    }

    public <R4> Tuple5<T1, T2, T3, R4, T5> mapFourth(
            Function<? super T4, ? extends R4> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple5<>(first, second, third, mapper.apply(fourth), fifth);
    }

    public <R5> Tuple5<T1, T2, T3, T4, R5> mapFifth(
            Function<? super T5, ? extends R5> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple5<>(first, second, third, fourth, mapper.apply(fifth));
    }

    public <R> R fold(Function5<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? extends R> function) {
        Objects.requireNonNull(function, "function");
        return function.apply(first, second, third, fourth, fifth);
    }
}
