// Generated by tools/generate_tuples.py; do not edit by hand.

package com.flechazo.hkt.tuple;

import com.flechazo.hkt.function.Function8;

import java.util.Objects;
import java.util.function.Function;

public record Tuple8<T1, T2, T3, T4, T5, T6, T7, T8>(
        T1 first,
        T2 second,
        T3 third,
        T4 fourth,
        T5 fifth,
        T6 sixth,
        T7 seventh,
        T8 eighth) {
    public Tuple8 {
        Objects.requireNonNull(first, "first");
        Objects.requireNonNull(second, "second");
        Objects.requireNonNull(third, "third");
        Objects.requireNonNull(fourth, "fourth");
        Objects.requireNonNull(fifth, "fifth");
        Objects.requireNonNull(sixth, "sixth");
        Objects.requireNonNull(seventh, "seventh");
        Objects.requireNonNull(eighth, "eighth");
    }

    public static <T1, T2, T3, T4, T5, T6, T7, T8> Tuple8<T1, T2, T3, T4, T5, T6, T7, T8> of(
            T1 first,
            T2 second,
            T3 third,
            T4 fourth,
            T5 fifth,
            T6 sixth,
            T7 seventh,
            T8 eighth) {
        return new Tuple8<>(first, second, third, fourth, fifth, sixth, seventh, eighth);
    }

    public <R1> Tuple8<R1, T2, T3, T4, T5, T6, T7, T8> mapFirst(
            Function<? super T1, ? extends R1> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple8<>(mapper.apply(first), second, third, fourth, fifth, sixth, seventh, eighth);
    }

    public <R2> Tuple8<T1, R2, T3, T4, T5, T6, T7, T8> mapSecond(
            Function<? super T2, ? extends R2> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple8<>(first, mapper.apply(second), third, fourth, fifth, sixth, seventh, eighth);
    }

    public <R3> Tuple8<T1, T2, R3, T4, T5, T6, T7, T8> mapThird(
            Function<? super T3, ? extends R3> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple8<>(first, second, mapper.apply(third), fourth, fifth, sixth, seventh, eighth);
    }

    public <R4> Tuple8<T1, T2, T3, R4, T5, T6, T7, T8> mapFourth(
            Function<? super T4, ? extends R4> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple8<>(first, second, third, mapper.apply(fourth), fifth, sixth, seventh, eighth);
    }

    public <R5> Tuple8<T1, T2, T3, T4, R5, T6, T7, T8> mapFifth(
            Function<? super T5, ? extends R5> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple8<>(first, second, third, fourth, mapper.apply(fifth), sixth, seventh, eighth);
    }

    public <R6> Tuple8<T1, T2, T3, T4, T5, R6, T7, T8> mapSixth(
            Function<? super T6, ? extends R6> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple8<>(first, second, third, fourth, fifth, mapper.apply(sixth), seventh, eighth);
    }

    public <R7> Tuple8<T1, T2, T3, T4, T5, T6, R7, T8> mapSeventh(
            Function<? super T7, ? extends R7> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple8<>(first, second, third, fourth, fifth, sixth, mapper.apply(seventh), eighth);
    }

    public <R8> Tuple8<T1, T2, T3, T4, T5, T6, T7, R8> mapEighth(
            Function<? super T8, ? extends R8> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple8<>(first, second, third, fourth, fifth, sixth, seventh, mapper.apply(eighth));
    }

    public <R> R fold(Function8<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? extends R> function) {
        Objects.requireNonNull(function, "function");
        return function.apply(first, second, third, fourth, fifth, sixth, seventh, eighth);
    }
}
