// Generated by tools/generate_tuples.py; do not edit by hand.

package com.flechazo.hkt.tuple;

import com.flechazo.hkt.function.Function7;

import java.util.Objects;
import java.util.function.Function;

public record Tuple7<T1, T2, T3, T4, T5, T6, T7>(
        T1 first,
        T2 second,
        T3 third,
        T4 fourth,
        T5 fifth,
        T6 sixth,
        T7 seventh) {
    public Tuple7 {
        Objects.requireNonNull(first, "first");
        Objects.requireNonNull(second, "second");
        Objects.requireNonNull(third, "third");
        Objects.requireNonNull(fourth, "fourth");
        Objects.requireNonNull(fifth, "fifth");
        Objects.requireNonNull(sixth, "sixth");
        Objects.requireNonNull(seventh, "seventh");
    }

    public static <T1, T2, T3, T4, T5, T6, T7> Tuple7<T1, T2, T3, T4, T5, T6, T7> of(
            T1 first,
            T2 second,
            T3 third,
            T4 fourth,
            T5 fifth,
            T6 sixth,
            T7 seventh) {
        return new Tuple7<>(first, second, third, fourth, fifth, sixth, seventh);
    }

    public <R1> Tuple7<R1, T2, T3, T4, T5, T6, T7> mapFirst(
            Function<? super T1, ? extends R1> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple7<>(mapper.apply(first), second, third, fourth, fifth, sixth, seventh);
    }

    public <R2> Tuple7<T1, R2, T3, T4, T5, T6, T7> mapSecond(
            Function<? super T2, ? extends R2> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple7<>(first, mapper.apply(second), third, fourth, fifth, sixth, seventh);
    }

    public <R3> Tuple7<T1, T2, R3, T4, T5, T6, T7> mapThird(
            Function<? super T3, ? extends R3> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple7<>(first, second, mapper.apply(third), fourth, fifth, sixth, seventh);
    }

    public <R4> Tuple7<T1, T2, T3, R4, T5, T6, T7> mapFourth(
            Function<? super T4, ? extends R4> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple7<>(first, second, third, mapper.apply(fourth), fifth, sixth, seventh);
    }

    public <R5> Tuple7<T1, T2, T3, T4, R5, T6, T7> mapFifth(
            Function<? super T5, ? extends R5> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple7<>(first, second, third, fourth, mapper.apply(fifth), sixth, seventh);
    }

    public <R6> Tuple7<T1, T2, T3, T4, T5, R6, T7> mapSixth(
            Function<? super T6, ? extends R6> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple7<>(first, second, third, fourth, fifth, mapper.apply(sixth), seventh);
    }

    public <R7> Tuple7<T1, T2, T3, T4, T5, T6, R7> mapSeventh(
            Function<? super T7, ? extends R7> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple7<>(first, second, third, fourth, fifth, sixth, mapper.apply(seventh));
    }

    public <R> R fold(Function7<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? extends R> function) {
        Objects.requireNonNull(function, "function");
        return function.apply(first, second, third, fourth, fifth, sixth, seventh);
    }
}
