// Generated by tools/generate_tuples.py; do not edit by hand.

package com.flechazo.hkt.tuple;

import com.flechazo.hkt.function.Function4;

import java.util.Objects;
import java.util.function.Function;

public record Tuple4<T1, T2, T3, T4>(
        T1 first,
        T2 second,
        T3 third,
        T4 fourth) {
    public Tuple4 {
        Objects.requireNonNull(first, "first");
        Objects.requireNonNull(second, "second");
        Objects.requireNonNull(third, "third");
        Objects.requireNonNull(fourth, "fourth");
    }

    public static <T1, T2, T3, T4> Tuple4<T1, T2, T3, T4> of(
            T1 first,
            T2 second,
            T3 third,
            T4 fourth) {
        return new Tuple4<>(first, second, third, fourth);
    }

    public <R1> Tuple4<R1, T2, T3, T4> mapFirst(
            Function<? super T1, ? extends R1> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple4<>(mapper.apply(first), second, third, fourth);
    }

    public <R2> Tuple4<T1, R2, T3, T4> mapSecond(
            Function<? super T2, ? extends R2> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple4<>(first, mapper.apply(second), third, fourth);
    }

    public <R3> Tuple4<T1, T2, R3, T4> mapThird(
            Function<? super T3, ? extends R3> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple4<>(first, second, mapper.apply(third), fourth);
    }

    public <R4> Tuple4<T1, T2, T3, R4> mapFourth(
            Function<? super T4, ? extends R4> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple4<>(first, second, third, mapper.apply(fourth));
    }

    public <R> R fold(Function4<? super T1, ? super T2, ? super T3, ? super T4, ? extends R> function) {
        Objects.requireNonNull(function, "function");
        return function.apply(first, second, third, fourth);
    }
}
