// Generated by tools/generate_tuples.py; do not edit by hand.

package com.flechazo.hkt.tuple;

import com.flechazo.hkt.function.Function6;

import java.util.Objects;
import java.util.function.Function;

public record Tuple6<T1, T2, T3, T4, T5, T6>(
        T1 first,
        T2 second,
        T3 third,
        T4 fourth,
        T5 fifth,
        T6 sixth) {
    public Tuple6 {
        Objects.requireNonNull(first, "first");
        Objects.requireNonNull(second, "second");
        Objects.requireNonNull(third, "third");
        Objects.requireNonNull(fourth, "fourth");
        Objects.requireNonNull(fifth, "fifth");
        Objects.requireNonNull(sixth, "sixth");
    }

    public static <T1, T2, T3, T4, T5, T6> Tuple6<T1, T2, T3, T4, T5, T6> of(
            T1 first,
            T2 second,
            T3 third,
            T4 fourth,
            T5 fifth,
            T6 sixth) {
        return new Tuple6<>(first, second, third, fourth, fifth, sixth);
    }

    public <R1> Tuple6<R1, T2, T3, T4, T5, T6> mapFirst(
            Function<? super T1, ? extends R1> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple6<>(mapper.apply(first), second, third, fourth, fifth, sixth);
    }

    public <R2> Tuple6<T1, R2, T3, T4, T5, T6> mapSecond(
            Function<? super T2, ? extends R2> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple6<>(first, mapper.apply(second), third, fourth, fifth, sixth);
    }

    public <R3> Tuple6<T1, T2, R3, T4, T5, T6> mapThird(
            Function<? super T3, ? extends R3> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple6<>(first, second, mapper.apply(third), fourth, fifth, sixth);
    }

    public <R4> Tuple6<T1, T2, T3, R4, T5, T6> mapFourth(
            Function<? super T4, ? extends R4> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple6<>(first, second, third, mapper.apply(fourth), fifth, sixth);
    }

    public <R5> Tuple6<T1, T2, T3, T4, R5, T6> mapFifth(
            Function<? super T5, ? extends R5> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple6<>(first, second, third, fourth, mapper.apply(fifth), sixth);
    }

    public <R6> Tuple6<T1, T2, T3, T4, T5, R6> mapSixth(
            Function<? super T6, ? extends R6> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple6<>(first, second, third, fourth, fifth, mapper.apply(sixth));
    }

    public <R> R fold(Function6<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? extends R> function) {
        Objects.requireNonNull(function, "function");
        return function.apply(first, second, third, fourth, fifth, sixth);
    }
}
