// Generated by tools/generate_tuples.py; do not edit by hand.

package com.flechazo.hkt.tuple;

import com.flechazo.hkt.function.Function13;

import java.util.Objects;
import java.util.function.Function;

public record Tuple13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(
        T1 first,
        T2 second,
        T3 third,
        T4 fourth,
        T5 fifth,
        T6 sixth,
        T7 seventh,
        T8 eighth,
        T9 ninth,
        T10 tenth,
        T11 eleventh,
        T12 twelfth,
        T13 thirteenth) {
    public Tuple13 {
        Objects.requireNonNull(first, "first");
        Objects.requireNonNull(second, "second");
        Objects.requireNonNull(third, "third");
        Objects.requireNonNull(fourth, "fourth");
        Objects.requireNonNull(fifth, "fifth");
        Objects.requireNonNull(sixth, "sixth");
        Objects.requireNonNull(seventh, "seventh");
        Objects.requireNonNull(eighth, "eighth");
        Objects.requireNonNull(ninth, "ninth");
        Objects.requireNonNull(tenth, "tenth");
        Objects.requireNonNull(eleventh, "eleventh");
        Objects.requireNonNull(twelfth, "twelfth");
        Objects.requireNonNull(thirteenth, "thirteenth");
    }

    public static <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> Tuple13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> of(
            T1 first,
            T2 second,
            T3 third,
            T4 fourth,
            T5 fifth,
            T6 sixth,
            T7 seventh,
            T8 eighth,
            T9 ninth,
            T10 tenth,
            T11 eleventh,
            T12 twelfth,
            T13 thirteenth) {
        return new Tuple13<>(first, second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth);
    }

    public <R1> Tuple13<R1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> mapFirst(
            Function<? super T1, ? extends R1> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple13<>(mapper.apply(first), second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth);
    }

    public <R2> Tuple13<T1, R2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> mapSecond(
            Function<? super T2, ? extends R2> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple13<>(first, mapper.apply(second), third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth);
    }

    public <R3> Tuple13<T1, T2, R3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> mapThird(
            Function<? super T3, ? extends R3> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple13<>(first, second, mapper.apply(third), fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth);
    }

    public <R4> Tuple13<T1, T2, T3, R4, T5, T6, T7, T8, T9, T10, T11, T12, T13> mapFourth(
            Function<? super T4, ? extends R4> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple13<>(first, second, third, mapper.apply(fourth), fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth);
    }

    public <R5> Tuple13<T1, T2, T3, T4, R5, T6, T7, T8, T9, T10, T11, T12, T13> mapFifth(
            Function<? super T5, ? extends R5> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple13<>(first, second, third, fourth, mapper.apply(fifth), sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth);
    }

    public <R6> Tuple13<T1, T2, T3, T4, T5, R6, T7, T8, T9, T10, T11, T12, T13> mapSixth(
            Function<? super T6, ? extends R6> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple13<>(first, second, third, fourth, fifth, mapper.apply(sixth), seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth);
    }

    public <R7> Tuple13<T1, T2, T3, T4, T5, T6, R7, T8, T9, T10, T11, T12, T13> mapSeventh(
            Function<? super T7, ? extends R7> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple13<>(first, second, third, fourth, fifth, sixth, mapper.apply(seventh), eighth, ninth, tenth, eleventh, twelfth, thirteenth);
    }

    public <R8> Tuple13<T1, T2, T3, T4, T5, T6, T7, R8, T9, T10, T11, T12, T13> mapEighth(
            Function<? super T8, ? extends R8> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple13<>(first, second, third, fourth, fifth, sixth, seventh, mapper.apply(eighth), ninth, tenth, eleventh, twelfth, thirteenth);
    }

    public <R9> Tuple13<T1, T2, T3, T4, T5, T6, T7, T8, R9, T10, T11, T12, T13> mapNinth(
            Function<? super T9, ? extends R9> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple13<>(first, second, third, fourth, fifth, sixth, seventh, eighth, mapper.apply(ninth), tenth, eleventh, twelfth, thirteenth);
    }

    public <R10> Tuple13<T1, T2, T3, T4, T5, T6, T7, T8, T9, R10, T11, T12, T13> mapTenth(
            Function<? super T10, ? extends R10> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple13<>(first, second, third, fourth, fifth, sixth, seventh, eighth, ninth, mapper.apply(tenth), eleventh, twelfth, thirteenth);
    }

    public <R11> Tuple13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R11, T12, T13> mapEleventh(
            Function<? super T11, ? extends R11> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple13<>(first, second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, mapper.apply(eleventh), twelfth, thirteenth);
    }

    public <R12> Tuple13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, R12, T13> mapTwelfth(
            Function<? super T12, ? extends R12> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple13<>(first, second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, mapper.apply(twelfth), thirteenth);
    }

    public <R13> Tuple13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, R13> mapThirteenth(
            Function<? super T13, ? extends R13> mapper) {
        Objects.requireNonNull(mapper, "mapper");
        return new Tuple13<>(first, second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, mapper.apply(thirteenth));
    }

    public <R> R fold(Function13<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? extends R> function) {
        Objects.requireNonNull(function, "function");
        return function.apply(first, second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth);
    }
}
