// Generated by tools/generate_function_products.py; do not edit by hand.

package com.flechazo.hkt;

import com.flechazo.hkt.function.*;

import java.util.function.BiFunction;
import java.util.function.Function;

public interface Applicative<F extends K1, Proof extends Applicative.Mu> extends Functor<F, Proof> {
    interface Mu extends Functor.Mu {
    }

    static <F extends K1, Proof extends Mu> Applicative<F, Proof> unbox(App<Proof, F> proofBox) {
        return (Applicative<F, Proof>) proofBox;
    }

    <A> App<F, A> of(A value);

    <A, B> App<F, B> ap(App<F, ? extends Function<A, B>> ff, App<F, A> fa);

    default <A, B, C> App<F, C> map2(
            App<F, A> fa, App<F, B> fb, BiFunction<? super A, ? super B, ? extends C> f) {
        return ap(map(a -> b -> f.apply(a, b), fa), fb);
    }

    default <T1, T2, T3, R> App<F, R> map3(
            App<F, T1> ft1,
            App<F, T2> ft2,
            App<F, T3> ft3,
            Function3<T1, T2, T3, R> f) {
        return ap(map2(ft1, ft2, f.curry2()), ft3);
    }

    default <T1, T2, T3, T4, R> App<F, R> map4(
            App<F, T1> ft1,
            App<F, T2> ft2,
            App<F, T3> ft3,
            App<F, T4> ft4,
            Function4<T1, T2, T3, T4, R> f) {
        return ap(map3(ft1, ft2, ft3, f.curry3()), ft4);
    }

    default <T1, T2, T3, T4, T5, R> App<F, R> map5(
            App<F, T1> ft1,
            App<F, T2> ft2,
            App<F, T3> ft3,
            App<F, T4> ft4,
            App<F, T5> ft5,
            Function5<T1, T2, T3, T4, T5, R> f) {
        return ap(map4(ft1, ft2, ft3, ft4, f.curry4()), ft5);
    }

    default <T1, T2, T3, T4, T5, T6, R> App<F, R> map6(
            App<F, T1> ft1,
            App<F, T2> ft2,
            App<F, T3> ft3,
            App<F, T4> ft4,
            App<F, T5> ft5,
            App<F, T6> ft6,
            Function6<T1, T2, T3, T4, T5, T6, R> f) {
        return ap(map5(ft1, ft2, ft3, ft4, ft5, f.curry5()), ft6);
    }

    default <T1, T2, T3, T4, T5, T6, T7, R> App<F, R> map7(
            App<F, T1> ft1,
            App<F, T2> ft2,
            App<F, T3> ft3,
            App<F, T4> ft4,
            App<F, T5> ft5,
            App<F, T6> ft6,
            App<F, T7> ft7,
            Function7<T1, T2, T3, T4, T5, T6, T7, R> f) {
        return ap(map6(ft1, ft2, ft3, ft4, ft5, ft6, f.curry6()), ft7);
    }

    default <T1, T2, T3, T4, T5, T6, T7, T8, R> App<F, R> map8(
            App<F, T1> ft1,
            App<F, T2> ft2,
            App<F, T3> ft3,
            App<F, T4> ft4,
            App<F, T5> ft5,
            App<F, T6> ft6,
            App<F, T7> ft7,
            App<F, T8> ft8,
            Function8<T1, T2, T3, T4, T5, T6, T7, T8, R> f) {
        return ap(map7(ft1, ft2, ft3, ft4, ft5, ft6, ft7, f.curry7()), ft8);
    }

    default <T1, T2, T3, T4, T5, T6, T7, T8, T9, R> App<F, R> map9(
            App<F, T1> ft1,
            App<F, T2> ft2,
            App<F, T3> ft3,
            App<F, T4> ft4,
            App<F, T5> ft5,
            App<F, T6> ft6,
            App<F, T7> ft7,
            App<F, T8> ft8,
            App<F, T9> ft9,
            Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R> f) {
        return ap(map8(ft1, ft2, ft3, ft4, ft5, ft6, ft7, ft8, f.curry8()), ft9);
    }

    default <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R> App<F, R> map10(
            App<F, T1> ft1,
            App<F, T2> ft2,
            App<F, T3> ft3,
            App<F, T4> ft4,
            App<F, T5> ft5,
            App<F, T6> ft6,
            App<F, T7> ft7,
            App<F, T8> ft8,
            App<F, T9> ft9,
            App<F, T10> ft10,
            Function10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R> f) {
        return ap(map9(ft1, ft2, ft3, ft4, ft5, ft6, ft7, ft8, ft9, f.curry9()), ft10);
    }

    default <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, R> App<F, R> map11(
            App<F, T1> ft1,
            App<F, T2> ft2,
            App<F, T3> ft3,
            App<F, T4> ft4,
            App<F, T5> ft5,
            App<F, T6> ft6,
            App<F, T7> ft7,
            App<F, T8> ft8,
            App<F, T9> ft9,
            App<F, T10> ft10,
            App<F, T11> ft11,
            Function11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, R> f) {
        return ap(map10(ft1, ft2, ft3, ft4, ft5, ft6, ft7, ft8, ft9, ft10, f.curry10()), ft11);
    }

    default <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, R> App<F, R> map12(
            App<F, T1> ft1,
            App<F, T2> ft2,
            App<F, T3> ft3,
            App<F, T4> ft4,
            App<F, T5> ft5,
            App<F, T6> ft6,
            App<F, T7> ft7,
            App<F, T8> ft8,
            App<F, T9> ft9,
            App<F, T10> ft10,
            App<F, T11> ft11,
            App<F, T12> ft12,
            Function12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, R> f) {
        return ap(map11(ft1, ft2, ft3, ft4, ft5, ft6, ft7, ft8, ft9, ft10, ft11, f.curry11()), ft12);
    }

    default <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, R> App<F, R> map13(
            App<F, T1> ft1,
            App<F, T2> ft2,
            App<F, T3> ft3,
            App<F, T4> ft4,
            App<F, T5> ft5,
            App<F, T6> ft6,
            App<F, T7> ft7,
            App<F, T8> ft8,
            App<F, T9> ft9,
            App<F, T10> ft10,
            App<F, T11> ft11,
            App<F, T12> ft12,
            App<F, T13> ft13,
            Function13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, R> f) {
        return ap(map12(ft1, ft2, ft3, ft4, ft5, ft6, ft7, ft8, ft9, ft10, ft11, ft12, f.curry12()), ft13);
    }

    default <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, R> App<F, R> map14(
            App<F, T1> ft1,
            App<F, T2> ft2,
            App<F, T3> ft3,
            App<F, T4> ft4,
            App<F, T5> ft5,
            App<F, T6> ft6,
            App<F, T7> ft7,
            App<F, T8> ft8,
            App<F, T9> ft9,
            App<F, T10> ft10,
            App<F, T11> ft11,
            App<F, T12> ft12,
            App<F, T13> ft13,
            App<F, T14> ft14,
            Function14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, R> f) {
        return ap(map13(ft1, ft2, ft3, ft4, ft5, ft6, ft7, ft8, ft9, ft10, ft11, ft12, ft13, f.curry13()), ft14);
    }

    default <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, R> App<F, R> map15(
            App<F, T1> ft1,
            App<F, T2> ft2,
            App<F, T3> ft3,
            App<F, T4> ft4,
            App<F, T5> ft5,
            App<F, T6> ft6,
            App<F, T7> ft7,
            App<F, T8> ft8,
            App<F, T9> ft9,
            App<F, T10> ft10,
            App<F, T11> ft11,
            App<F, T12> ft12,
            App<F, T13> ft13,
            App<F, T14> ft14,
            App<F, T15> ft15,
            Function15<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, R> f) {
        return ap(map14(ft1, ft2, ft3, ft4, ft5, ft6, ft7, ft8, ft9, ft10, ft11, ft12, ft13, ft14, f.curry14()), ft15);
    }

    default <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, R> App<F, R> map16(
            App<F, T1> ft1,
            App<F, T2> ft2,
            App<F, T3> ft3,
            App<F, T4> ft4,
            App<F, T5> ft5,
            App<F, T6> ft6,
            App<F, T7> ft7,
            App<F, T8> ft8,
            App<F, T9> ft9,
            App<F, T10> ft10,
            App<F, T11> ft11,
            App<F, T12> ft12,
            App<F, T13> ft13,
            App<F, T14> ft14,
            App<F, T15> ft15,
            App<F, T16> ft16,
            Function16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, R> f) {
        return ap(map15(ft1, ft2, ft3, ft4, ft5, ft6, ft7, ft8, ft9, ft10, ft11, ft12, ft13, ft14, ft15, f.curry15()), ft16);
    }

}
