// Generated by tools/generate_function_products.py; do not edit by hand.

package com.flechazo.hkt;

import com.flechazo.hkt.function.*;

import java.util.function.BiFunction;
import java.util.function.Function;

public interface Products {
    static <F extends K1, T1> P1<F, T1> of(Applicative<F, ?> applicative, App<F, T1> t1) {
        return new P1<>(applicative, t1);
    }

    record P1<F extends K1, T1>(
            Applicative<F, ?> applicative,
            App<F, T1> t1) {

        <T2> P2<F, T1, T2> and(App<F, T2> t2) {
            return new P2<>(applicative, t1, t2);
        }

        <R> App<F, R> apply(Function<? super T1, ? extends R> function) {
            return applicative.map(function, t1);
        }
    }

    record P2<F extends K1, T1, T2>(
            Applicative<F, ?> applicative,
            App<F, T1> t1,
            App<F, T2> t2) {

        <T3> P3<F, T1, T2, T3> and(App<F, T3> t3) {
            return new P3<>(applicative, t1, t2, t3);
        }

        <R> App<F, R> apply(BiFunction<? super T1, ? super T2, ? extends R> function) {
            return applicative.map2(t1, t2, function);
        }
    }

    record P3<F extends K1, T1, T2, T3>(
            Applicative<F, ?> applicative,
            App<F, T1> t1,
            App<F, T2> t2,
            App<F, T3> t3) {

        <T4> P4<F, T1, T2, T3, T4> and(App<F, T4> t4) {
            return new P4<>(applicative, t1, t2, t3, t4);
        }

        <R> App<F, R> apply(Function3<? super T1, ? super T2, ? super T3, ? extends R> function) {
            return applicative.map3(t1, t2, t3, function::apply);
        }
    }

    record P4<F extends K1, T1, T2, T3, T4>(
            Applicative<F, ?> applicative,
            App<F, T1> t1,
            App<F, T2> t2,
            App<F, T3> t3,
            App<F, T4> t4) {

        <T5> P5<F, T1, T2, T3, T4, T5> and(App<F, T5> t5) {
            return new P5<>(applicative, t1, t2, t3, t4, t5);
        }

        <R> App<F, R> apply(Function4<? super T1, ? super T2, ? super T3, ? super T4, ? extends R> function) {
            return applicative.map4(t1, t2, t3, t4, function::apply);
        }
    }

    record P5<F extends K1, T1, T2, T3, T4, T5>(
            Applicative<F, ?> applicative,
            App<F, T1> t1,
            App<F, T2> t2,
            App<F, T3> t3,
            App<F, T4> t4,
            App<F, T5> t5) {

        <T6> P6<F, T1, T2, T3, T4, T5, T6> and(App<F, T6> t6) {
            return new P6<>(applicative, t1, t2, t3, t4, t5, t6);
        }

        <R> App<F, R> apply(Function5<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? extends R> function) {
            return applicative.map5(t1, t2, t3, t4, t5, function::apply);
        }
    }

    record P6<F extends K1, T1, T2, T3, T4, T5, T6>(
            Applicative<F, ?> applicative,
            App<F, T1> t1,
            App<F, T2> t2,
            App<F, T3> t3,
            App<F, T4> t4,
            App<F, T5> t5,
            App<F, T6> t6) {

        <T7> P7<F, T1, T2, T3, T4, T5, T6, T7> and(App<F, T7> t7) {
            return new P7<>(applicative, t1, t2, t3, t4, t5, t6, t7);
        }

        <R> App<F, R> apply(Function6<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? extends R> function) {
            return applicative.map6(t1, t2, t3, t4, t5, t6, function::apply);
        }
    }

    record P7<F extends K1, T1, T2, T3, T4, T5, T6, T7>(
            Applicative<F, ?> applicative,
            App<F, T1> t1,
            App<F, T2> t2,
            App<F, T3> t3,
            App<F, T4> t4,
            App<F, T5> t5,
            App<F, T6> t6,
            App<F, T7> t7) {

        <T8> P8<F, T1, T2, T3, T4, T5, T6, T7, T8> and(App<F, T8> t8) {
            return new P8<>(applicative, t1, t2, t3, t4, t5, t6, t7, t8);
        }

        <R> App<F, R> apply(Function7<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? extends R> function) {
            return applicative.map7(t1, t2, t3, t4, t5, t6, t7, function::apply);
        }
    }

    record P8<F extends K1, T1, T2, T3, T4, T5, T6, T7, T8>(
            Applicative<F, ?> applicative,
            App<F, T1> t1,
            App<F, T2> t2,
            App<F, T3> t3,
            App<F, T4> t4,
            App<F, T5> t5,
            App<F, T6> t6,
            App<F, T7> t7,
            App<F, T8> t8) {

        <T9> P9<F, T1, T2, T3, T4, T5, T6, T7, T8, T9> and(App<F, T9> t9) {
            return new P9<>(applicative, t1, t2, t3, t4, t5, t6, t7, t8, t9);
        }

        <R> App<F, R> apply(Function8<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? extends R> function) {
            return applicative.map8(t1, t2, t3, t4, t5, t6, t7, t8, function::apply);
        }
    }

    record P9<F extends K1, T1, T2, T3, T4, T5, T6, T7, T8, T9>(
            Applicative<F, ?> applicative,
            App<F, T1> t1,
            App<F, T2> t2,
            App<F, T3> t3,
            App<F, T4> t4,
            App<F, T5> t5,
            App<F, T6> t6,
            App<F, T7> t7,
            App<F, T8> t8,
            App<F, T9> t9) {

        <T10> P10<F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> and(App<F, T10> t10) {
            return new P10<>(applicative, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10);
        }

        <R> App<F, R> apply(Function9<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? extends R> function) {
            return applicative.map9(t1, t2, t3, t4, t5, t6, t7, t8, t9, function::apply);
        }
    }

    record P10<F extends K1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(
            Applicative<F, ?> applicative,
            App<F, T1> t1,
            App<F, T2> t2,
            App<F, T3> t3,
            App<F, T4> t4,
            App<F, T5> t5,
            App<F, T6> t6,
            App<F, T7> t7,
            App<F, T8> t8,
            App<F, T9> t9,
            App<F, T10> t10) {

        <T11> P11<F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> and(App<F, T11> t11) {
            return new P11<>(applicative, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11);
        }

        <R> App<F, R> apply(Function10<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? extends R> function) {
            return applicative.map10(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, function::apply);
        }
    }

    record P11<F extends K1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(
            Applicative<F, ?> applicative,
            App<F, T1> t1,
            App<F, T2> t2,
            App<F, T3> t3,
            App<F, T4> t4,
            App<F, T5> t5,
            App<F, T6> t6,
            App<F, T7> t7,
            App<F, T8> t8,
            App<F, T9> t9,
            App<F, T10> t10,
            App<F, T11> t11) {

        <T12> P12<F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> and(App<F, T12> t12) {
            return new P12<>(applicative, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12);
        }

        <R> App<F, R> apply(Function11<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? extends R> function) {
            return applicative.map11(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, function::apply);
        }
    }

    record P12<F extends K1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(
            Applicative<F, ?> applicative,
            App<F, T1> t1,
            App<F, T2> t2,
            App<F, T3> t3,
            App<F, T4> t4,
            App<F, T5> t5,
            App<F, T6> t6,
            App<F, T7> t7,
            App<F, T8> t8,
            App<F, T9> t9,
            App<F, T10> t10,
            App<F, T11> t11,
            App<F, T12> t12) {

        <T13> P13<F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> and(App<F, T13> t13) {
            return new P13<>(applicative, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13);
        }

        <R> App<F, R> apply(Function12<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? extends R> function) {
            return applicative.map12(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, function::apply);
        }
    }

    record P13<F extends K1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(
            Applicative<F, ?> applicative,
            App<F, T1> t1,
            App<F, T2> t2,
            App<F, T3> t3,
            App<F, T4> t4,
            App<F, T5> t5,
            App<F, T6> t6,
            App<F, T7> t7,
            App<F, T8> t8,
            App<F, T9> t9,
            App<F, T10> t10,
            App<F, T11> t11,
            App<F, T12> t12,
            App<F, T13> t13) {

        <T14> P14<F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> and(App<F, T14> t14) {
            return new P14<>(applicative, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14);
        }

        <R> App<F, R> apply(Function13<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? extends R> function) {
            return applicative.map13(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, function::apply);
        }
    }

    record P14<F extends K1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(
            Applicative<F, ?> applicative,
            App<F, T1> t1,
            App<F, T2> t2,
            App<F, T3> t3,
            App<F, T4> t4,
            App<F, T5> t5,
            App<F, T6> t6,
            App<F, T7> t7,
            App<F, T8> t8,
            App<F, T9> t9,
            App<F, T10> t10,
            App<F, T11> t11,
            App<F, T12> t12,
            App<F, T13> t13,
            App<F, T14> t14) {

        <T15> P15<F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> and(App<F, T15> t15) {
            return new P15<>(applicative, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15);
        }

        <R> App<F, R> apply(Function14<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? super T14, ? extends R> function) {
            return applicative.map14(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, function::apply);
        }
    }

    record P15<F extends K1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(
            Applicative<F, ?> applicative,
            App<F, T1> t1,
            App<F, T2> t2,
            App<F, T3> t3,
            App<F, T4> t4,
            App<F, T5> t5,
            App<F, T6> t6,
            App<F, T7> t7,
            App<F, T8> t8,
            App<F, T9> t9,
            App<F, T10> t10,
            App<F, T11> t11,
            App<F, T12> t12,
            App<F, T13> t13,
            App<F, T14> t14,
            App<F, T15> t15) {

        <T16> P16<F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> and(App<F, T16> t16) {
            return new P16<>(applicative, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16);
        }

        <R> App<F, R> apply(Function15<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? super T14, ? super T15, ? extends R> function) {
            return applicative.map15(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, function::apply);
        }
    }

    record P16<F extends K1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(
            Applicative<F, ?> applicative,
            App<F, T1> t1,
            App<F, T2> t2,
            App<F, T3> t3,
            App<F, T4> t4,
            App<F, T5> t5,
            App<F, T6> t6,
            App<F, T7> t7,
            App<F, T8> t8,
            App<F, T9> t9,
            App<F, T10> t10,
            App<F, T11> t11,
            App<F, T12> t12,
            App<F, T13> t13,
            App<F, T14> t14,
            App<F, T15> t15,
            App<F, T16> t16) {

        <R> App<F, R> apply(Function16<? super T1, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? super T14, ? super T15, ? super T16, ? extends R> function) {
            return applicative.map16(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, function::apply);
        }
    }

}
