from pathlib import Path


MAX_ARITY = 16
ROOT = Path(__file__).resolve().parents[1]
HKT_DIR = ROOT / "src/main/java/com/flechazo/hkt"
CAPABILITY_DIR = HKT_DIR / "business/capability"
CONTROL_DIR = HKT_DIR / "business/control"

ORDINALS = [
    "first", "second", "third", "fourth", "fifth", "sixth", "seventh", "eighth",
    "ninth", "tenth", "eleventh", "twelfth", "thirteenth", "fourteenth", "fifteenth", "sixteenth",
]


def function_type(arity: int, types: list[str], result: str) -> str:
    args = [f"? super {type_name}" for type_name in types] + [f"? extends {result}"]
    return f"Function{arity}<{', '.join(args)}>"


def method_name(arity: int) -> str:
    return "zipWithAccum" if arity == 2 else f"zipWith{arity}Accum"


def method_parameters(arity: int) -> tuple[list[str], list[str], list[str]]:
    types = [f"T{index}" for index in range(2, arity + 1)]
    names = ORDINALS[1:arity]
    parameters = [
        f"            Accumulating<E, {type_name}> {name},"
        for type_name, name in zip(types, names)
    ]
    parameters.append(
        f"            {function_type(arity, ['A'] + types, 'R')} combiner) {{")
    return types, names, parameters


def generated_header() -> str:
    return "// Generated by tools/generate_accumulating.py; do not edit by hand.\n"


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def generate_accumulating() -> str:
    lines = [
        generated_header(),
        "package com.flechazo.hkt.business.capability;",
        "",
        "import com.flechazo.hkt.tuple.*;",
        "import com.flechazo.hkt.function.*;",
        "",
        "import java.util.function.BiFunction;",
        "",
        "public interface Accumulating<E, A> extends Composable<A> {",
        "    <B, C> Accumulating<E, C> zipWithAccum(",
        "            Accumulating<E, B> other,",
        "            BiFunction<? super A, ? super B, ? extends C> combiner);",
        "",
        "    default <B, C, D> Accumulating<E, D> zipWith3Accum(",
        "            Accumulating<E, B> second,",
        "            Accumulating<E, C> third,",
        "            Function3<? super A, ? super B, ? super C, ? extends D> combiner) {",
        "        Accumulating<E, Tuple2<A, B>> partial = zipWithAccum(second, Tuple2::new);",
        "        return partial.zipWithAccum(third,",
        "                (values, value) -> combiner.apply(values.first(), values.second(), value));",
        "    }",
        "",
    ]
    for arity in range(4, MAX_ARITY + 1):
        types, names, parameters = method_parameters(arity)
        lines.append(
            f"    default <{', '.join(types + ['R'])}> Accumulating<E, R> {method_name(arity)}(")
        lines.extend(parameters)
        previous_arity = arity - 1
        previous_types = ["A"] + types[:-1]
        previous_args = ", ".join(names[:-1] + [f"Tuple{previous_arity}::of"])
        lines.extend([
            f"        Accumulating<E, Tuple{previous_arity}<{', '.join(previous_types)}>> partial =",
            f"                {method_name(previous_arity)}({previous_args});",
        ])
        values = [f"values.{name}()" for name in ORDINALS[:previous_arity]] + ["value"]
        lines.extend([
            f"        return partial.zipWithAccum({names[-1]},",
            f"                (values, value) -> combiner.apply({', '.join(values)}));",
            "    }",
            "",
        ])
    lines.extend([
        "    Accumulating<E, A> andAlso(Accumulating<E, ?> other);",
        "",
        "    <B> Accumulating<E, B> andThen(Accumulating<E, B> other);",
        "}",
        "",
    ])
    return "\n".join(lines)


def generate_validation_accumulating() -> str:
    lines = [
        generated_header(),
        "package com.flechazo.hkt.business.control;",
        "",
        "import com.flechazo.hkt.tuple.Tuple2;",
        "import com.flechazo.hkt.Validated;",
        "import com.flechazo.hkt.business.capability.Accumulating;",
        "import com.flechazo.hkt.function.*;",
        "",
        "import java.util.function.BiFunction;",
        "",
        "interface ValidationAccumulating<E, A> extends Accumulating<E, A> {",
        "    @Override",
        "    default <B, R> ValidationPath<E, R> zipWithAccum(",
        "            Accumulating<E, B> other,",
        "            BiFunction<? super A, ? super B, ? extends R> combiner) {",
        "        if (!(other instanceof ValidationPath<?, ?>)) {",
        "            throw new IllegalArgumentException(\"zipWithAccum requires ValidationPath, got: \" + other.getClass());",
        "        }",
        "        ValidationPath<E, A> left = self();",
        "        ValidationPath<E, B> right = narrow(other);",
        "        Validated<E, A> leftValue = left.run();",
        "        Validated<E, B> rightValue = right.run();",
        "        if (leftValue.isValid() && rightValue.isValid()) {",
        "            return new ValidationPath<>(",
        "                    Validated.valid(combiner.apply(leftValue.value(), rightValue.value())),",
        "                    left.semigroup());",
        "        }",
        "        if (leftValue.isInvalid() && rightValue.isInvalid()) {",
        "            return new ValidationPath<>(",
        "                    Validated.invalid(left.semigroup().combine(leftValue.error(), rightValue.error())),",
        "                    left.semigroup());",
        "        }",
        "        return leftValue.isInvalid()",
        "                ? new ValidationPath<>(Validated.invalid(leftValue.error()), left.semigroup())",
        "                : new ValidationPath<>(Validated.invalid(rightValue.error()), left.semigroup());",
        "    }",
        "",
        "    @Override",
        "    default <B, C, R> ValidationPath<E, R> zipWith3Accum(",
        "            Accumulating<E, B> second,",
        "            Accumulating<E, C> third,",
        "            Function3<? super A, ? super B, ? super C, ? extends R> combiner) {",
        "        return zipWithAccum(second, Tuple2::new)",
        "                .zipWithAccum(third,",
        "                        (values, value) -> combiner.apply(values.first(), values.second(), value));",
        "    }",
        "",
    ]
    for arity in range(4, MAX_ARITY + 1):
        types, names, parameters = method_parameters(arity)
        lines.extend([
            "    @Override",
            f"    default <{', '.join(types + ['R'])}> ValidationPath<E, R> {method_name(arity)}(",
        ])
        lines.extend(parameters)
        arguments = ", ".join(names + ["combiner"])
        lines.extend([
            f"        return narrow(Accumulating.super.{method_name(arity)}({arguments}));",
            "    }",
            "",
        ])
    lines.extend([
        "    @SuppressWarnings(\"unchecked\")",
        "    private ValidationPath<E, A> self() {",
        "        return (ValidationPath<E, A>) this;",
        "    }",
        "",
        "    @SuppressWarnings(\"unchecked\")",
        "    private static <E, A> ValidationPath<E, A> narrow(Accumulating<E, A> value) {",
        "        return (ValidationPath<E, A>) value;",
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    write(CAPABILITY_DIR / "Accumulating.java", generate_accumulating())
    write(CONTROL_DIR / "ValidationAccumulating.java", generate_validation_accumulating())


if __name__ == "__main__":
    main()
