from pathlib import Path


MAX_ARITY = 16
ROOT = Path(__file__).resolve().parents[1]
FUNCTION_DIR = ROOT / "src/main/java/com/flechazo/hkt/function"
HKT_DIR = ROOT / "src/main/java/com/flechazo/hkt"


def type_names(n: int) -> list[str]:
    return [f"T{i}" for i in range(1, n + 1)]


def value_names(n: int, prefix: str = "t") -> list[str]:
    return [f"{prefix}{i}" for i in range(1, n + 1)]


def nested_function(types: list[str], result: str) -> str:
    if len(types) == 1:
        return f"Function<{types[0]}, {result}>"
    return f"Function<{types[0]}, {nested_function(types[1:], result)}>"


def curried_tail_type(types: list[str], result: str) -> str:
    return function_type(len(types), types, result)


def function_type(arity: int, args: list[str], result: str) -> str:
    if arity == 1:
        return f"Function<{args[0]}, {result}>"
    if arity == 2:
        return f"BiFunction<{args[0]}, {args[1]}, {result}>"
    return f"Function{arity}<{', '.join(args + [result])}>"


def lambda_prefix(names: list[str]) -> str:
    if len(names) == 1:
        return f"{names[0]} -> "
    return f"({', '.join(names)}) -> "


def generated_header() -> str:
    return "// Generated by tools/generate_function_products.py; do not edit by hand.\n"


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def generate_function(arity: int) -> str:
    types = type_names(arity)
    args = value_names(arity)
    generic = ", ".join(types + ["R"])
    params = ", ".join(f"{t} {v}" for t, v in zip(types, args))
    apply_args = ", ".join(args)
    lines = [
        generated_header(),
        "package com.flechazo.hkt.function;",
        "",
        "import java.util.function.BiFunction;",
        "import java.util.function.Function;",
        "",
        "@FunctionalInterface",
        f"public interface Function{arity}<{generic}> {{",
        f"    R apply({params});",
        "",
    ]

    for fixed in range(1, arity):
        fixed_types = types[:fixed]
        fixed_args = args[:fixed]
        remaining_args = args[fixed:]
        tail = curried_tail_type(types[fixed:], "R")
        return_type = function_type(fixed, fixed_types, tail)
        method = "curry" if fixed == 1 else f"curry{fixed}"
        body = lambda_prefix(fixed_args)
        if remaining_args:
            body += lambda_prefix(remaining_args)
        body += f"apply({apply_args})"
        lines.extend([
            f"    default {return_type} {method}() {{",
            f"        return {body};",
            "    }",
            "",
        ])

    lines.append("}\n")
    return "\n".join(lines)


def generate_applicative() -> str:
    lines = [
        generated_header(),
        "package com.flechazo.hkt;",
        "",
        "import com.flechazo.hkt.function.*;",
        "",
        "import java.util.function.BiFunction;",
        "import java.util.function.Function;",
        "",
        "public interface Applicative<F extends K1, Proof extends Applicative.Mu> extends Functor<F, Proof> {",
        "    interface Mu extends Functor.Mu {",
        "    }",
        "",
        "    static <F extends K1, Proof extends Mu> Applicative<F, Proof> unbox(App<Proof, F> proofBox) {",
        "        return (Applicative<F, Proof>) proofBox;",
        "    }",
        "",
        "    <A> App<F, A> of(A value);",
        "",
        "    <A, B> App<F, B> ap(App<F, ? extends Function<A, B>> ff, App<F, A> fa);",
        "",
        "    default <A, B, C> App<F, C> map2(",
        "            App<F, A> fa, App<F, B> fb, BiFunction<? super A, ? super B, ? extends C> f) {",
        "        return ap(map(a -> b -> f.apply(a, b), fa), fb);",
        "    }",
        "",
    ]

    for arity in range(3, MAX_ARITY + 1):
        types = type_names(arity)
        apps = value_names(arity, "ft")
        values = value_names(arity, "t")
        generic = ", ".join(types + ["R"])
        params = [f"App<F, {t}> {app}" for t, app in zip(types, apps)]
        params.append(f"Function{arity}<{', '.join(types + ['R'])}> f")
        lines.append(f"    default <{generic}> App<F, R> map{arity}(")
        for index, param in enumerate(params):
            comma = "," if index < len(params) - 1 else ") {"
            lines.append(f"            {param}{comma}")
        prefix_apps = ", ".join(apps[:-1])
        curry = "curry" if arity == 2 else f"curry{arity - 1}"
        lines.append(f"        return ap(map{arity - 1}({prefix_apps}, f.{curry}()), {apps[-1]});")
        lines.append("    }")
        lines.append("")

    lines.append("}\n")
    return "\n".join(lines)


def wildcard_function_type(arity: int, types: list[str], result: str) -> str:
    args = [f"? super {t}" for t in types] + [f"? extends {result}"]
    if arity == 1:
        return f"Function<{args[0]}, {args[1]}>"
    if arity == 2:
        return f"BiFunction<{args[0]}, {args[1]}, {args[2]}>"
    return f"Function{arity}<{', '.join(args)}>"


def generate_product_record(arity: int) -> list[str]:
    types = type_names(arity)
    apps = value_names(arity, "t")
    generic = ", ".join(["F extends K1"] + types)
    fields = ["Applicative<F, ?> applicative"] + [f"App<F, {t}> {app}" for t, app in zip(types, apps)]
    lines = [
        f"    record P{arity}<{generic}>(",
    ]
    for index, field in enumerate(fields):
        comma = "," if index < len(fields) - 1 else ") {"
        lines.append(f"            {field}{comma}")
    lines.append("")

    if arity < MAX_ARITY:
        next_type = f"T{arity + 1}"
        current_args = ", ".join(["applicative"] + apps + [f"t{arity + 1}"])
        next_generic = ", ".join(["F"] + types + [next_type])
        lines.extend([
            f"        <{next_type}> P{arity + 1}<{next_generic}> and(App<F, {next_type}> t{arity + 1}) {{",
            f"            return new P{arity + 1}<>({current_args});",
            "        }",
            "",
        ])

    function = wildcard_function_type(arity, types, "R")
    lines.extend([
        f"        <R> App<F, R> apply({function} function) {{",
    ])
    if arity == 1:
        lines.append("            return applicative.map(function::apply, t1);")
    elif arity == 2:
        lines.append("            return applicative.map2(t1, t2, function::apply);")
    else:
        app_params = ", ".join(apps)
        lines.append(f"            return applicative.map{arity}({app_params}, function::apply);")
    lines.extend([
        "        }",
        "    }",
        "",
    ])
    return lines


def generate_products() -> str:
    lines = [
        generated_header(),
        "package com.flechazo.hkt;",
        "",
        "import com.flechazo.hkt.function.*;",
        "",
        "import java.util.function.BiFunction;",
        "import java.util.function.Function;",
        "",
        "public interface Products {",
        "    static <F extends K1, T1> P1<F, T1> of(Applicative<F, ?> applicative, App<F, T1> t1) {",
        "        return new P1<>(applicative, t1);",
        "    }",
        "",
    ]
    for arity in range(1, MAX_ARITY + 1):
        lines.extend(generate_product_record(arity))
    lines.append("}\n")
    return "\n".join(lines)


def main() -> None:
    for arity in range(3, MAX_ARITY + 1):
        write(FUNCTION_DIR / f"Function{arity}.java", generate_function(arity))
    write(HKT_DIR / "Applicative.java", generate_applicative())
    write(HKT_DIR / "Products.java", generate_products())


if __name__ == "__main__":
    main()
