from pathlib import Path


MAX_ARITY = 16
ROOT = Path(__file__).resolve().parents[1]
HKT_DIR = ROOT / "src/main/java/com/flechazo/hkt"
CAPABILITY_DIR = HKT_DIR / "business/capability/combinable"

ORDINALS = [
    "first", "second", "third", "fourth", "fifth", "sixth", "seventh", "eighth",
    "ninth", "tenth", "eleventh", "twelfth", "thirteenth", "fourteenth", "fifteenth", "sixteenth",
]

PATHS = [
    ("business/control", "MaybeCombinable", "MaybePath", []),
    ("business/control", "EitherCombinable", "EitherPath", ["E"]),
    ("business/control", "TryCombinable", "TryPath", []),
    ("business/control", "ListCombinable", "ListPath", []),
    ("business/control", "ValidationCombinable", "ValidationPath", ["E"]),
    ("business/context", "ReaderCombinable", "ReaderPath", ["R"]),
    ("business/context", "WriterCombinable", "WriterPath", ["W"]),
    ("business/context", "StateCombinable", "WithStatePath", ["S"]),
    ("business/effect", "LazyCombinable", "LazyPath", []),
    ("business/effect", "FutureCombinable", "CompletableFuturePath", []),
    ("business/effect", "VTaskCombinable", "VTaskPath", []),
    ("business/effect", "IOCombinable", "IOPath", []),
    ("business/stream", "VStreamCombinable", "VStreamPath", []),
]


def function_type(arity: int, types: list[str], result: str) -> str:
    args = [f"? super {type_name}" for type_name in types] + [f"? extends {result}"]
    return f"Function{arity}<{', '.join(args)}>"


def method_name(arity: int) -> str:
    return "zipWith" if arity == 2 else f"zipWith{arity}"


def method_parameters(arity: int) -> tuple[list[str], list[str], list[str]]:
    types = [f"T{index}" for index in range(2, arity + 1)]
    names = ORDINALS[1:arity]
    parameters = [
        f"            Combinable<{type_name}> {name},"
        for type_name, name in zip(types, names)
    ]
    parameters.append(
        f"            {function_type(arity, ['A'] + types, 'OUT')} combiner) {{")
    return types, names, parameters


def generated_header() -> str:
    return "// Generated by tools/generate_combinable.py; do not edit by hand.\n"


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def generate_combinable() -> str:
    lines = [
        generated_header(),
        "package com.flechazo.hkt.business.capability.combinable;",
        "",
        "import com.flechazo.hkt.business.capability.Composable;",
        "import com.flechazo.hkt.function.*;",
        "import com.flechazo.hkt.tuple.*;",
        "",
        "import java.util.function.BiFunction;",
        "",
        "public interface Combinable<A> extends Composable<A> {",
        "    <B, R> Combinable<R> zipWith(",
        "            Combinable<B> other,",
        "            BiFunction<? super A, ? super B, ? extends R> combiner);",
        "",
    ]
    for arity in range(3, MAX_ARITY + 1):
        types, names, parameters = method_parameters(arity)
        lines.append(
            f"    default <{', '.join(types + ['OUT'])}> Combinable<OUT> {method_name(arity)}(")
        lines.extend(parameters)
        previous_arity = arity - 1
        previous_types = ["A"] + types[:-1]
        if previous_arity == 2:
            previous_args = ", ".join(names[:-1] + ["Tuple2::new"])
        else:
            previous_args = ", ".join(names[:-1] + [f"Tuple{previous_arity}::of"])
        lines.extend([
            f"        Combinable<Tuple{previous_arity}<{', '.join(previous_types)}>> partial =",
            f"                {method_name(previous_arity)}({previous_args});",
        ])
        values = [f"values.{name}()" for name in ORDINALS[:previous_arity]] + ["value"]
        lines.extend([
            f"        return partial.zipWith({names[-1]},",
            f"                (values, value) -> combiner.apply({', '.join(values)}));",
            "    }",
            "",
        ])
    lines.extend(["}", ""])
    return "\n".join(lines)


def path_type(path_class: str, context_types: list[str], value_type: str) -> str:
    return f"{path_class}<{', '.join(context_types + [value_type])}>"


def generate_path_interface(
        package_name: str,
        interface_name: str,
        path_class: str,
        context_types: list[str]) -> str:
    interface_generics = context_types + ["A"]
    lines = [
        generated_header(),
        f"package com.flechazo.hkt.{package_name};",
        "",
        "import com.flechazo.hkt.business.capability.combinable.Combinable;",
        "import com.flechazo.hkt.function.*;",
        "",
        f"public interface {interface_name}<{', '.join(interface_generics)}> extends Combinable<A> {{",
    ]
    for arity in range(3, MAX_ARITY + 1):
        types, names, parameters = method_parameters(arity)
        lines.extend([
            "    @Override",
            f"    default <{', '.join(types + ['OUT'])}> {path_type(path_class, context_types, 'OUT')} {method_name(arity)}(",
        ])
        lines.extend(parameters)
        arguments = ", ".join(names + ["combiner"])
        lines.extend([
            f"        return narrow(Combinable.super.{method_name(arity)}({arguments}));",
            "    }",
            "",
        ])
    narrow_generics = context_types + ["A"]
    lines.extend([
        "    @SuppressWarnings(\"unchecked\")",
        f"    private static <{', '.join(narrow_generics)}> {path_type(path_class, context_types, 'A')} narrow(",
        "            Combinable<A> value) {",
        f"        return ({path_type(path_class, context_types, 'A')}) value;",
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    write(CAPABILITY_DIR / "Combinable.java", generate_combinable())
    for package_path, interface_name, path_class, context_types in PATHS:
        package_name = "business.capability.combinable"
        output_dir = CAPABILITY_DIR
        write(
            output_dir / f"{interface_name}.java",
            generate_path_interface(package_name, interface_name, path_class, context_types)
            .replace(
                "import com.flechazo.hkt.function.*;",
                f"import com.flechazo.hkt.{package_path.replace('/', '.')}.{path_class};\n"
                "import com.flechazo.hkt.function.*;",
            ),
        )


if __name__ == "__main__":
    main()
