from pathlib import Path


MAX_ARITY = 16
ROOT = Path(__file__).resolve().parents[1]
TUPLE_DIR = ROOT / "src/main/java/com/flechazo/hkt/tuple"

ORDINALS = [
    "first", "second", "third", "fourth", "fifth", "sixth", "seventh", "eighth",
    "ninth", "tenth", "eleventh", "twelfth", "thirteenth", "fourteenth", "fifteenth", "sixteenth",
]


def type_names(arity: int) -> list[str]:
    return [f"T{index}" for index in range(1, arity + 1)]


def generated_header() -> str:
    return "// Generated by tools/generate_tuples.py; do not edit by hand.\n"


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def generate_tuple(arity: int) -> str:
    types = type_names(arity)
    names = ORDINALS[:arity]
    generic = ", ".join(types)
    lines = [
        generated_header(),
        "package com.flechazo.hkt.tuple;",
        "",
        f"import com.flechazo.hkt.function.Function{arity};",
        "",
        "import java.util.Objects;",
        "import java.util.function.Function;",
        "",
        f"public record Tuple{arity}<{generic}>(",
    ]
    for index, (type_name, name) in enumerate(zip(types, names)):
        comma = "," if index < arity - 1 else ") {"
        lines.append(f"        {type_name} {name}{comma}")
    lines.append(f"    public Tuple{arity} {{")
    for name in names:
        lines.append(f"        Objects.requireNonNull({name}, \"{name}\");")
    lines.extend([
        "    }",
        "",
        f"    public static <{generic}> Tuple{arity}<{generic}> of(",
    ])
    for index, (type_name, name) in enumerate(zip(types, names)):
        comma = "," if index < arity - 1 else ") {"
        lines.append(f"            {type_name} {name}{comma}")
    lines.extend([
        f"        return new Tuple{arity}<>({', '.join(names)});",
        "    }",
        "",
    ])
    for index, (type_name, name) in enumerate(zip(types, names)):
        mapped_type = f"R{index + 1}"
        result_types = types.copy()
        result_types[index] = mapped_type
        constructor_args = names.copy()
        constructor_args[index] = f"mapper.apply({name})"
        method_name = f"map{name[0].upper()}{name[1:]}"
        lines.extend([
            f"    public <{mapped_type}> Tuple{arity}<{', '.join(result_types)}> {method_name}(",
            f"            Function<? super {type_name}, ? extends {mapped_type}> mapper) {{",
            "        Objects.requireNonNull(mapper, \"mapper\");",
            f"        return new Tuple{arity}<>({', '.join(constructor_args)});",
            "    }",
            "",
        ])
    function_args = [f"? super {type_name}" for type_name in types] + ["? extends R"]
    lines.extend([
        f"    public <R> R fold(Function{arity}<{', '.join(function_args)}> function) {{",
        "        Objects.requireNonNull(function, \"function\");",
        f"        return function.apply({', '.join(names)});",
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    for arity in range(4, MAX_ARITY + 1):
        write(TUPLE_DIR / f"Tuple{arity}.java", generate_tuple(arity))


if __name__ == "__main__":
    main()
