// Generated by tools/generate_accumulating.py; do not edit by hand.

package com.flechazo.hkt.business.capability;

import com.flechazo.hkt.function.*;
import com.flechazo.hkt.tuple.*;

import java.util.function.BiFunction;

public interface Accumulating<E, A> extends Composable<A> {
    <B, C> Accumulating<E, C> zipWithAccum(
            Accumulating<E, B> other,
            BiFunction<? super A, ? super B, ? extends C> combiner);

    default <B, C, D> Accumulating<E, D> zipWith3Accum(
            Accumulating<E, B> second,
            Accumulating<E, C> third,
            Function3<? super A, ? super B, ? super C, ? extends D> combiner) {
        Accumulating<E, Tuple2<A, B>> partial = zipWithAccum(second, Tuple2::new);
        return partial.zipWithAccum(third,
                (values, value) -> combiner.apply(values.first(), values.second(), value));
    }

    default <T2, T3, T4, R> Accumulating<E, R> zipWith4Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Function4<? super A, ? super T2, ? super T3, ? super T4, ? extends R> combiner) {
        Accumulating<E, Tuple3<A, T2, T3>> partial =
                zipWith3Accum(second, third, Tuple3::of);
        return partial.zipWithAccum(fourth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), value));
    }

    default <T2, T3, T4, T5, R> Accumulating<E, R> zipWith5Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Function5<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? extends R> combiner) {
        Accumulating<E, Tuple4<A, T2, T3, T4>> partial =
                zipWith4Accum(second, third, fourth, Tuple4::of);
        return partial.zipWithAccum(fifth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), value));
    }

    default <T2, T3, T4, T5, T6, R> Accumulating<E, R> zipWith6Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Function6<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? extends R> combiner) {
        Accumulating<E, Tuple5<A, T2, T3, T4, T5>> partial =
                zipWith5Accum(second, third, fourth, fifth, Tuple5::of);
        return partial.zipWithAccum(sixth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), value));
    }

    default <T2, T3, T4, T5, T6, T7, R> Accumulating<E, R> zipWith7Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Function7<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? extends R> combiner) {
        Accumulating<E, Tuple6<A, T2, T3, T4, T5, T6>> partial =
                zipWith6Accum(second, third, fourth, fifth, sixth, Tuple6::of);
        return partial.zipWithAccum(seventh,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), value));
    }

    default <T2, T3, T4, T5, T6, T7, T8, R> Accumulating<E, R> zipWith8Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Accumulating<E, T8> eighth,
            Function8<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? extends R> combiner) {
        Accumulating<E, Tuple7<A, T2, T3, T4, T5, T6, T7>> partial =
                zipWith7Accum(second, third, fourth, fifth, sixth, seventh, Tuple7::of);
        return partial.zipWithAccum(eighth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), values.seventh(), value));
    }

    default <T2, T3, T4, T5, T6, T7, T8, T9, R> Accumulating<E, R> zipWith9Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Accumulating<E, T8> eighth,
            Accumulating<E, T9> ninth,
            Function9<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? extends R> combiner) {
        Accumulating<E, Tuple8<A, T2, T3, T4, T5, T6, T7, T8>> partial =
                zipWith8Accum(second, third, fourth, fifth, sixth, seventh, eighth, Tuple8::of);
        return partial.zipWithAccum(ninth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), values.seventh(), values.eighth(), value));
    }

    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, R> Accumulating<E, R> zipWith10Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Accumulating<E, T8> eighth,
            Accumulating<E, T9> ninth,
            Accumulating<E, T10> tenth,
            Function10<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? extends R> combiner) {
        Accumulating<E, Tuple9<A, T2, T3, T4, T5, T6, T7, T8, T9>> partial =
                zipWith9Accum(second, third, fourth, fifth, sixth, seventh, eighth, ninth, Tuple9::of);
        return partial.zipWithAccum(tenth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), values.seventh(), values.eighth(), values.ninth(), value));
    }

    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, R> Accumulating<E, R> zipWith11Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Accumulating<E, T8> eighth,
            Accumulating<E, T9> ninth,
            Accumulating<E, T10> tenth,
            Accumulating<E, T11> eleventh,
            Function11<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? extends R> combiner) {
        Accumulating<E, Tuple10<A, T2, T3, T4, T5, T6, T7, T8, T9, T10>> partial =
                zipWith10Accum(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, Tuple10::of);
        return partial.zipWithAccum(eleventh,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), values.seventh(), values.eighth(), values.ninth(), values.tenth(), value));
    }

    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, R> Accumulating<E, R> zipWith12Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Accumulating<E, T8> eighth,
            Accumulating<E, T9> ninth,
            Accumulating<E, T10> tenth,
            Accumulating<E, T11> eleventh,
            Accumulating<E, T12> twelfth,
            Function12<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? extends R> combiner) {
        Accumulating<E, Tuple11<A, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>> partial =
                zipWith11Accum(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, Tuple11::of);
        return partial.zipWithAccum(twelfth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), values.seventh(), values.eighth(), values.ninth(), values.tenth(), values.eleventh(), value));
    }

    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, R> Accumulating<E, R> zipWith13Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Accumulating<E, T8> eighth,
            Accumulating<E, T9> ninth,
            Accumulating<E, T10> tenth,
            Accumulating<E, T11> eleventh,
            Accumulating<E, T12> twelfth,
            Accumulating<E, T13> thirteenth,
            Function13<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? extends R> combiner) {
        Accumulating<E, Tuple12<A, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>> partial =
                zipWith12Accum(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, Tuple12::of);
        return partial.zipWithAccum(thirteenth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), values.seventh(), values.eighth(), values.ninth(), values.tenth(), values.eleventh(), values.twelfth(), value));
    }

    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, R> Accumulating<E, R> zipWith14Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Accumulating<E, T8> eighth,
            Accumulating<E, T9> ninth,
            Accumulating<E, T10> tenth,
            Accumulating<E, T11> eleventh,
            Accumulating<E, T12> twelfth,
            Accumulating<E, T13> thirteenth,
            Accumulating<E, T14> fourteenth,
            Function14<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? super T14, ? extends R> combiner) {
        Accumulating<E, Tuple13<A, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>> partial =
                zipWith13Accum(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth, Tuple13::of);
        return partial.zipWithAccum(fourteenth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), values.seventh(), values.eighth(), values.ninth(), values.tenth(), values.eleventh(), values.twelfth(), values.thirteenth(), value));
    }

    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, R> Accumulating<E, R> zipWith15Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Accumulating<E, T8> eighth,
            Accumulating<E, T9> ninth,
            Accumulating<E, T10> tenth,
            Accumulating<E, T11> eleventh,
            Accumulating<E, T12> twelfth,
            Accumulating<E, T13> thirteenth,
            Accumulating<E, T14> fourteenth,
            Accumulating<E, T15> fifteenth,
            Function15<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? super T14, ? super T15, ? extends R> combiner) {
        Accumulating<E, Tuple14<A, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>> partial =
                zipWith14Accum(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth, fourteenth, Tuple14::of);
        return partial.zipWithAccum(fifteenth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), values.seventh(), values.eighth(), values.ninth(), values.tenth(), values.eleventh(), values.twelfth(), values.thirteenth(), values.fourteenth(), value));
    }

    default <T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, R> Accumulating<E, R> zipWith16Accum(
            Accumulating<E, T2> second,
            Accumulating<E, T3> third,
            Accumulating<E, T4> fourth,
            Accumulating<E, T5> fifth,
            Accumulating<E, T6> sixth,
            Accumulating<E, T7> seventh,
            Accumulating<E, T8> eighth,
            Accumulating<E, T9> ninth,
            Accumulating<E, T10> tenth,
            Accumulating<E, T11> eleventh,
            Accumulating<E, T12> twelfth,
            Accumulating<E, T13> thirteenth,
            Accumulating<E, T14> fourteenth,
            Accumulating<E, T15> fifteenth,
            Accumulating<E, T16> sixteenth,
            Function16<? super A, ? super T2, ? super T3, ? super T4, ? super T5, ? super T6, ? super T7, ? super T8, ? super T9, ? super T10, ? super T11, ? super T12, ? super T13, ? super T14, ? super T15, ? super T16, ? extends R> combiner) {
        Accumulating<E, Tuple15<A, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>> partial =
                zipWith15Accum(second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth, eleventh, twelfth, thirteenth, fourteenth, fifteenth, Tuple15::of);
        return partial.zipWithAccum(sixteenth,
                (values, value) -> combiner.apply(values.first(), values.second(), values.third(), values.fourth(), values.fifth(), values.sixth(), values.seventh(), values.eighth(), values.ninth(), values.tenth(), values.eleventh(), values.twelfth(), values.thirteenth(), values.fourteenth(), values.fifteenth(), value));
    }

    Accumulating<E, A> andAlso(Accumulating<E, ?> other);

    <B> Accumulating<E, B> andThen(Accumulating<E, B> other);
}
